services:
  db:
    image: postgres:latest
    container_name: rizztorante-db
    restart: always
    env_file:
      - .env
    environment:
      APP_DB_PORT: ${APP_DB_PORT}
      APP_DB_HOST_PORT: ${APP_DB_HOST_PORT}
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "${APP_DB_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  cache:
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    container_name: rizztorante-cache
    env_file:
      - .env
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rizztorante-app
    environment:
      NODE_ENV: ${NODE_ENV}
      APP_API_PORT: ${APP_API_PORT}
      DB_HOST: db
      APP_DB_NAME: ${APP_DB_NAME}
      APP_DB_USERNAME: ${APP_DB_USERNAME}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      APP_DB_PORT: ${APP_DB_HOST_PORT}
      APP_DB_HOST_PORT: ${APP_DB_HOST_PORT}
      SESSION_NAME: ${SESSION_NAME}
      SESSION_SECRET: ${SESSION_SECRET}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      PAYMENT_SUCCESS_URL: ${PAYMENT_SUCCESS_URL}
      PAYMENT_ERROR_URL: ${PAYMENT_ERROR_URL}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_REGION: ${S3_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    ports:
      - "${APP_API_PORT}:${APP_API_PORT}"
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: rizztorante-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db

volumes:
  redis_data:
  pgdata:
